### ISSUE TITLE
源码编译make -j4报错

### ISSUE THREAD

**Issue by yujie-hong** [iammcy/BFLC-demo#1]
操作系统：Ubuntu 20.04.1 LTS
FISCO-BCOS：2.7.2
根据README使用root用户一步步操作，working_dir=/root，执行make -j4的时候报错，请问改如何解决
![2021-05-30_143755](https://user-images.githubusercontent.com/68286740/120094883-83a5e380-c155-11eb-9d06-13497fab402d.png)

**Comment by iammcy** [comment]
在CMakeLists.txt配置步骤中，不是直接添加target_link_libraries(precompiled PRIVATE ... nlohmann_json)这句命令，是在原有的target_link_libraries命令中加入nlohmann_json目标链接库的意思，“...”代表其他目标链接库，可能错误发生在这里，可以再仔细看看<working_dir>/FISCO-BCOS/libprecompiled/CMakeLists.txt的配置说明，感谢您的反馈！

**Comment by iammcy** [comment]
> 操作系统：Ubuntu 20.04.1 LTS
> FISCO-BCOS：2.7.2
> 根据README使用root用户一步步操作，working_dir=/root，执行make -j4的时候报错，请问如何解决
> ![2021-05-30_143755](https://user-images.githubusercontent.com/68286740/120094883-83a5e380-c155-11eb-9d06-13497fab402d.png)

在C.txt配置步骤中，不是直接添加target_link_libraries(precompiled PRIVATE ... nlohmann_json)这句命令，是在原有的target_link_libraries命令中加入nlohmann_json目标链接库的英文，“...”代表其他目标链接库，可能错误发生在这里，可以再仔细查看<working_dir>/FISCO-BCOS/libprecompiled/CMakeLists.txt的配置说明，感谢您的反馈！

**Comment by yujie-hong** [comment]
确实是这个问题，感觉帮助
