### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by pingping1122** [iammcy/BFLC-demo#11]
楼主，请问一下，main中local_scoring函数是没有交叉验证的是吗?
若足够数量更新，则当前的委员会节点直接计分,若一个委员会计分数量达到聚合数，之后的委员会节点是不是就不再计分了？

**Comment by pingping1122** [comment]
也就是多个委员会对同一个更新的计分 没有求均值过程是吗？只保留第一个委员会的打分？

**Comment by iammcy** [comment]
> 楼主，请问一下，main中local_scoring函数是没有交叉验证的是吗? 若足够数量更新，则当前的委员会节点直接计分,若一个委员会计分数量达到聚合数，之后的委员会节点是不是就不再计分了？

local_scoring函数中没有交叉验证，就是用本地数据对所有收集的更新验证；
设定是所有委员会节点都上传了计分，才会聚合更新。


> 也就是多个委员会对同一个更新的计分 没有求均值过程是吗？只保留第一个委员会的打分？

对，是没有求均值，但是用了同一个更新对应所有委员会计分的中位数

**Comment by pingping1122** [comment]
楼主  想请问一下初始模型是合约下发的  
【1】怎么没有看到ser_w和ser_b在哪里设置的初始值啊？
【2】

**Comment by iammcy** [comment]
有的，在预编译合约的cpp文件中调用了InitGlobalModel函数，里面创建了Model对象，同时调用了默认的构造函数(在头文件中已定义，设置了初始值均为0)
