### ISSUE TITLE
原理问题

### ISSUE THREAD

**Issue by dl12300** [iammcy/BFLC-demo#14]
您好，原论文中提到使用“两个不同的区块来存储全局模型和局部更新”，请问这部分内容体现在您代码中的哪个部分呢？还有您是怎么把奖励分配给相应的节点的？您在这个项目中如何选择的委员会成员？

**Comment by iammcy** [comment]
模型的存储设置和奖励分配不在公开代码里，demo项目代码里具体包括整体框架构建和合约的自动化执行委员会选举和模型聚合等。选择委员会成员是合约根据当前轮次客户端上传的模型质量进行选择从而得到下一轮次的委员会成员。
