### ISSUE TITLE
cmake ..编译问题

### ISSUE THREAD

**Issue by PengchengUp** [iammcy/BFLC-demo#15]
您好，在源码编译，第4步，出现了如下问题：
rpcheng@ubuntu:~/FISCO-BCOS/build$ cmake ..
CMake Error at CMakeLists.txt:44 (message):
  The submodules were not downloaded! GIT_SUBMODULE was turned off or failed.
  Please execute:

    git submodule update --init

-- Configuring incomplete, errors occurred!

请问这是什么原因呢，以及如何解决
感谢

**Comment by iammcy** [comment]
可能是部分依赖库下载失败了，建议尝试多次执行或按照README中关于cmake出错问题的解决方案进行解决。
