### ISSUE TITLE
请问需要多大的GPU

### ISSUE THREAD

**Issue by 1ofvc** [iammcy/BFLC-demo#18]

**Comment by iammcy** [comment]
您好！代码默认设置是使用cpu跑的，您也可以设置用GPU跑，目前使用GPU跑还没测试过需要多大的显存，由于模型比较小并且客户端数量不多所以显存占用应该不大。

**Comment by 1ofvc** [comment]
> 您好！代码默认设置是使用cpu跑的，您也可以设置用GPU跑，目前使用GPU跑还没测试过需要多大的显存，由于模型比较小并且客户端数量不多所以显存占用应该不大。

谢谢，确实是用cpu跑的，谢谢您啦～
