### ISSUE TITLE
make -j4网络编译出错

### ISSUE THREAD

**Issue by YhanJude** [iammcy/BFLC-demo#2]
[用了两种方法还是编译不了，编辑hosts文件和直接下载libs文件都不行，请问怎么回事呀]

**Comment by iammcy** [comment]
如果在编译过程中是显示下载依赖库失败，应该是机器网络的问题，可以多尝试几次。如果显示其他错误信息，可以提供一下错误信息，方便我们解决

**Comment by YhanJude** [comment]
就是这样的，一直卡在这里了
![QQ图片20210607100434](https://user-images.githubusercontent.com/35054695/120949769-d3009b00-c777-11eb-986a-d052af37f1af.png)

**Comment by xiby** [comment]
你好，请按照报错提示，提供一下  /home/jude/FISCO-BCOS/deps/src/evmone-stamp/evmone-configure-err.log  日志文件里的报错信息，方便排查问题，谢谢。

**Comment by YhanJude** [comment]
![QQ图片20210607160233](https://user-images.githubusercontent.com/35054695/120982400-4374df80-c7ab-11eb-8485-afcf9e25ba50.png)
![QQ图片20210607160903](https://user-images.githubusercontent.com/35054695/120982430-4a9bed80-c7ab-11eb-8885-d2692a11dc48.png)

**Comment by xiby** [comment]
反馈已收到，非常感谢！

看了下，日志里面提示是权限问题，你可以检查一下当前用户是否有文件写入权限。

**Comment by YhanJude** [comment]
是要直接在root用户下面执行吗

**Comment by xiby** [comment]
也不一定，需要在你clone FISCO的那个用户下面执行，如果你是以root用户执行的git clone，或者使用了sudo，你就需要在root用户下面执行

**Comment by YhanJude** [comment]
![QQ图片20210607221227](https://user-images.githubusercontent.com/35054695/121032040-7a63e900-c7dd-11eb-91b1-e741aab38ed1.png)
改了网络问题，也一直卡在这里，请问这个怎么解决呀

**Comment by xiby** [comment]
你好，应该是你手动下载的包可能不完整，所以在make的时候依赖被删除了，我这边从  https://codeload.github.com/oneapi-src/oneTBB/tar.gz/v2020.3 这里下载下来的依赖计算sha256是所需要的，所以建议先手动下载该依赖，然后上传到dep/src目录下。

**Comment by YhanJude** [comment]
请问学习哪些技术可以自行搭建这样一个框架

**Comment by iammcy** [comment]
1. 区块链部分：我们采用的是FISCO BCOS开源平台，可以根据自身的需求进行了解
- 官方文档：[https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/](url)
- 官方源码：[https://github.com/FISCO-BCOS/FISCO-BCOS](url)
2. 客户端模型搭建和训练：可以自行了解一些深度学习框架，如tensorflow、pytorch等
3. 涉及语言：solidity、c++、python等

**Comment by iammcy** [comment]
1. 区块链部分：我们采用的是FISCO BCOS开源平台，可以根据自身的需求进行了解
- 官方文档：[https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/](url)
- 官方源码：[https://github.com/FISCO-BCOS/FISCO-BCOS](url)
2. 客户端模型搭建和训练：可以自行了解一些深度学习框架，如tensorflow、pytorch等
3. 涉及语言：solidity、c++、python等

**Comment by iammcy** [comment]
1. 区块链部分：我们采用的是FISCO BCOS开源平台，可以根据自身的需求进行了解
- 官方文档：[https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/](url)
- 官方源码：[https://github.com/FISCO-BCOS/FISCO-BCOS](url)
2. 客户端模型搭建和训练：可以自行了解一些深度学习框架，如tensorflow、pytorch等
3. 涉及语言：solidity、c++、python等

**Comment by YhanJude** [comment]
好的，非常感谢
