### ISSUE TITLE
您好，请问这是什么问题

### ISSUE THREAD

**Issue by mynameisfys** [iammcy/BFLC-demo#25]
![2221](https://user-images.githubusercontent.com/61084461/229328535-0846df9e-138c-4f7c-95ff-96568649d935.PNG)

**Comment by iammcy** [comment]
您好，可以查看一下已解决的issue #1 ，里面有相关的疑问回复

**Comment by mynameisfys** [comment]
已解决，方法很有效，感谢您的回答。
