### ISSUE TITLE
请问为什么找不到tensorflow-gpu

### ISSUE THREAD

**Issue by mynameisfys** [iammcy/BFLC-demo#27]
![q1](https://user-images.githubusercontent.com/61084461/229458049-5eafdab4-ee68-42c4-880d-9308b591c654.PNG)

**Comment by iammcy** [comment]
这只是个人创建的虚拟环境名称，请进入自己已有的环境，或没有相关虚拟环境则按照readme后面的说明执行命令创建

**Comment by mynameisfys** [comment]
python 版本是3.8以上可以吗

**Comment by iammcy** [comment]
可以试一下，另外由于main.py里需要用到tensorflow等库，因此，后面需要安装相关的库到该环境中，相关库的版本说明在readme也列出来了
