### ISSUE TITLE
请问这个错误怎么解决

### ISSUE THREAD

**Issue by mynameisfys** [iammcy/BFLC-demo#28]
![22](https://user-images.githubusercontent.com/61084461/229717734-4ef07515-d739-467b-8f8d-4942eb54b80a.PNG)

**Comment by iammcy** [comment]
可能是因为这个[原因](https://blog.csdn.net/qq_33976344/article/details/120113114)，这个不是该demo引起的报错

**Comment by mynameisfys** [comment]
好的，谢谢
