### ISSUE TITLE
用户代码准备

### ISSUE THREAD

**Issue by YhanJude** [iammcy/BFLC-demo#3]
请问这些和后面的代码写在哪里呀
![QQ图片20210608170600](https://user-images.githubusercontent.com/35054695/121157071-d2e9c380-c87b-11eb-8249-0053d334b558.png)

**Comment by iammcy** [comment]
这部分（第4步）和下面的（第5步）接口调用是对main.py文件的部分重要代码的介绍，所以如果在环境配置好的前提下，可以直接运行main.py文件（即第6步）

**Comment by YhanJude** [comment]
好的，感谢
