### ISSUE TITLE
请问这是什么问题

### ISSUE THREAD

**Issue by mynameisfys** [iammcy/BFLC-demo#30]
![222](https://user-images.githubusercontent.com/61084461/230242308-426e4c5d-39fc-470b-ba18-06d3c2fe3b89.PNG)

**Comment by iammcy** [comment]
py脚本文件需要用python解释器运行（应按照readme说明中在已创建的虚拟环境中运行`python main.py`命令），建议先可以网上检索与该demo无关问题的解决方案并在closed issue上查看有帮助的回复可以快速解决问题。
