### ISSUE TITLE
运行main.py报错

### ISSUE THREAD

**Issue by Lorenz5622** [iammcy/BFLC-demo#36]
<img width="368" alt="a9a54c7569d243b6e1729b86941346d" src="https://user-images.githubusercontent.com/91588395/231047750-d760a697-fac5-415c-b38c-5b26f1945cb1.png">
老师您好，我在最后一步运行main.py的时候出现了这个报错。请问缺少/bin/logs是什么意思，该如何解决这个问题？

上面是我在~路径中执行时遇到的问题。在python-sdk路径下执行main.py报错如下：
<img width="370" alt="image" src="https://user-images.githubusercontent.com/91588395/231053648-397decfd-484d-4611-87e6-ba80f654e2ee.png">

**Comment by Lorenz5622** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/91588395/231168436-83a31e05-dcc9-4d22-af41-b492a03d331d.png">
成功安装tensorflow了，但是现在运行main.py会大量报错，请问该如何解决呢？

**Comment by GuangguangLu** [comment]
我遇到了一模一样的问题，请问您解决了吗？  欢迎讨论：q：82316637

**Comment by GuangguangLu** [comment]
![image](https://user-images.githubusercontent.com/97269757/231968167-d2459125-5051-4f60-a484-ac1eadf8eb34.png)

**Comment by Lorenz5622** [comment]
不太记得了，你要不先把
<img width="649" alt="image" src="https://user-images.githubusercontent.com/91588395/231977847-11f4c3f6-7a38-42b5-a89c-3afa73b75828.png">
这两步重做一下？

**Comment by GuangguangLu** [comment]
成功了，太谢谢你了，就是这里的问题，启动所有的节点就行了。&nbsp; &nbsp;不能关闭节点。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月14日(星期五) 下午3:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [iammcy/BFLC-demo] 运行main.py报错 (Issue #36)





 
不太记得了，你要不先把
 
 这两步重做一下？
