### ISSUE TITLE
运行main.py报错

### ISSUE THREAD

**Issue by PengchengUp** [iammcy/BFLC-demo#43]
![image](https://user-images.githubusercontent.com/58407733/233536036-3d22f476-8bfb-4744-be05-b6e52a0bd91f.png)
请问这是什么问题

**Comment by Lorenz5622** [comment]
您好，我也遇到了这个问题。请问您是怎么解决的，可以分享一下吗？多谢。

**Comment by PengchengUp** [comment]
> 您好，我也遇到了这个问题。请问您是怎么解决的，可以分享一下吗？多谢。
可以尝试重新配置一遍

**Comment by PengchengUp** [comment]
> 您好，我也遇到了这个问题。请问您是怎么解决的，可以分享一下吗？多谢。

可以尝试重新配置一遍
