### ISSUE TITLE
缺少set_from_account_signer

### ISSUE THREAD

**Issue by YhanJude** [iammcy/BFLC-demo#5]
请问缺少这个怎么回事呀
![QQ图片20210623172832](https://user-images.githubusercontent.com/35054695/123073145-c010ea80-d448-11eb-8e85-7db861be3dad.png)

**Comment by iammcy** [comment]
您好，为了模拟多个客户端访问区块链，本项目采用切换账户签名的方法对源码进行了修改。参考“客户端配置”下的“4. 用户代码准备”中最后一点描述的“在 <working_dir>/python-sdk/client/bcosclient.py 加入对应的函数”
