### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by LY-5028** [iammcy/BFLC-demo#6]
你好请问一下 在make j4时  发现CommitteePrecompiled.cpp.o出现了错误
![Uploading image.png…]()

**Comment by LY-5028** [comment]
![image](https://user-images.githubusercontent.com/63282850/128474898-cb930436-31e6-434f-8c26-12d0077dc1d9.png)

**Comment by iammcy** [comment]
您好，您可以先仅对官方的源码项目进行编译，编译没有出现问题后，再加入本项目的CommitteePrecompiled预编译合约进行编译，如果再出现报错信息，请提供一下操作过程和报错信息。

**Comment by LY-5028** [comment]
您好  我重新编译了一下   以下是按照步骤的操作
![image](https://user-images.githubusercontent.com/63282850/128502211-8c89e746-3ab9-419b-9470-1174a8cfdf15.png)
![image](https://user-images.githubusercontent.com/63282850/128502301-6af7fd4f-967d-4b89-b638-c26a5ba73c25.png)
![image](https://user-images.githubusercontent.com/63282850/128502391-7deec9db-ee4f-4352-865c-6866c9e22e6d.png)
![image](https://user-images.githubusercontent.com/63282850/128502431-9ca56a66-4577-4e8f-90d4-14b80450a327.png)
zui'h最后一个问编译的出错

**Comment by LY-5028** [comment]
![image](https://user-images.githubusercontent.com/63282850/128502999-a0e5fa16-6c05-42f0-8d21-fd6980a169e2.png)

这个是不用预编译时编译成功的

**Comment by LY-5028** [comment]
抱歉  我知道我哪里出错了  谢谢您的指导
