### ISSUE TITLE
多机部署配置

### ISSUE THREAD

**Issue by HuangJie98** [iammcy/BFLC-demo#8]
作者你好，关于多机部署我有两个问题，期待回复，谢谢了！
Q1：每个区块链节点都要部署python-sdk吗？
Q2：*<working_dir>/python-sdk/client_config.py*中的remote_rpcurl与channel_host该如何配置？（我现在有五个节点）
![8G@S88UI50Q1LT8S}U G(TD](https://user-images.githubusercontent.com/60546464/133182809-2ea06e9f-c555-4aaa-85d5-385ed1f08841.png)

**Comment by iammcy** [comment]
你好，对于区块链多机部署：
A1：每个机器均需要下载python-sdk作为访问区块链的python工具
A2：<working_dir>/python-sdk/client_config.py中一般采用的channel协议，如图里的client_protocol设置，channel_host应该是设置成建区块链节点时的ip，remote_rpcurl可以不用改；但如果改成rpc协议时，remote_rpcurl应该设置成建链时的ip，加上任意一个区块链节点的端口。
（关键应该是跨机建链部分的配置，[具体可以参考文档](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/)）
