### ISSUE TITLE
全局模型设计

### ISSUE THREAD

**Issue by ddc123456** [iammcy/BFLC-demo#9]
您好，我看了您编写的CommitteePrecompiled.h文件中对于模型的定义，这个是原论文中使用的alexnet模型吗？请问这个预编译有推荐的教程么，对于预编译合约的编写您有什么建议么？谢谢！
![image](https://user-images.githubusercontent.com/73273183/137130699-16710858-6036-4a8f-9429-37543abb8ec4.png)

**Comment by LY-5028** [comment]
您好，我想请问一下  在我实验的过程中  训练第一轮结果后  出现了timeout的错误是因为什么
![image](https://user-images.githubusercontent.com/63282850/137594549-911bd9bf-bc08-4c5c-91b2-c30afa93ea7b.png)

**Comment by iammcy** [comment]
你可以检查一下创建的区块链节点有没有问题：
1. 看一下是不是创建的节点都启动了：`ps -ef | grep -v grep | grep fisco-bcos`
2. 看一下各个节点中执行fisco程序的输出，如：`tail -f ~/fisco/nodes/127.0.0.1/node0/nohup.out`

**Comment by LY-5028** [comment]
原有的是设置了客户端的参与率吗？？

**Comment by EvilLevis** [comment]
> 您好，我想请问一下 在我实验的过程中 训练第一轮结果后 出现了timeout的错误是因为什么 ![image](https://user-images.githubusercontent.com/63282850/137594549-911bd9bf-bc08-4c5c-91b2-c30afa93ea7b.png)

您好，可以请问一下您当时是如何解决这个time out 的问题么，我也遇到了相同的问题

**Comment by quinter770** [comment]
> > 您好，我想请问一下 在我实验的过程中 训练第一轮结果后 出现了timeout的错误是因为什么 ![image](https://user-images.githubusercontent.com/63282850/137594549-911bd9bf-bc08-4c5c-91b2-c30afa93ea7b.png)
> 
> 您好，可以请问一下您当时是如何解决这个time out 的问题么，我也遇到了相同的问题

你好你这个问题解决了吗？我现在也是出现了训练一轮后报timeout的错误
